repos:
  # -------------------------------
  # Secret scanning
  # -------------------------------
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
        args: ["protect", "--verbose"]
